Repository owncloud/QA, pull requests merged in 2018-10, with the labels that each got.

#596 update Smoke Tests
  Server/Test_Plan_Smoke_Test.md
Labels: 3 - To review

#599 add Two Factor Authentication to scenarios
  Server/Test_Plan_Smoke_Test.md
Labels: 3 - To review, QA, QA-team

#597 Add test plan PR 2306: Av. offline jobs
  Mobile/Android/Templates/Release_2.9.0/2308-jobs_for_available_offline.md
Labels: Android
